### ISSUE TITLE
Managed to delete a field?

### ISSUE THREAD

**Issue by damithc** [CS2103-AY1819S1-T10-3/main#22]
One of you guys said you had difficulty deleting a Person field last week. Did you manage to do it later? @alexehrs

**Comment by alexehrs** [comment]
Nope, not yet. Gonna try again after lunch. I will also make a post on the forum about it.

**Comment by damithc** [comment]
> Nope, not yet. Gonna try again after lunch. I will also make a post on the forum about it.

See https://github.com/nus-cs2103-AY1819S1/forum/issues/60

**Comment by alexehrs** [comment]
Thank you @damithc for posting on the forum on my behalf! We'll see if I get the issue resolved.
