### ISSUE TITLE
Full comments + Fixes for v1.1

### ISSUE THREAD

**Issue by RussellOng95** [CS2103-AY1819S1-T10-3/main#30]
> Overall:
> Good job on meeting all requirements for the v1.1 team component. However, some areas need more work. Hope you can tackle those areas in upcoming features.
> 
> Some detailed feedback:
> 
> ReadMe adoc
> Product description still refers to AB-4's functionality (point 2). [done]
> Describe what LearnV is in the homepage [done]
> Remove top SE EDU nav bar and link to LOs [done]
> View on GitHub link [done]
> Results in 404. Check that you have correctly followed the steps for auto-publishing of docs [done]
> 
> Contact Us adoc
> Details have to be updated [not done]
> 
> About Us adoc
> 
> Photos aren't visible. Please update ASAP. [everyone do]
> Developer Guide adoc
> Looks like the auto publish is not properly enabled. The page is all cluttered up and not being displayed in the correct manner. [formatting to be done by @alexehrs]
> Two groups of Group User stories provided. Use either one, preferably the one grouped by priority [not done]
> Use case steps are too complex and not atomic. Suggest splitting up into multiple steps as in the comment provided. [not done]
> Too many steps in this one line. Ideally it should be split up as the MSS and the exception workflow. Something like:
> MSS:
> User enters a word to add to the review list.
> System adds word to the dictionary.
> System prompts user with word successfully added message
> System displays newly added word's meaning
> Use case ends
> Extensions:
> 2a. Word already exists in the dictionary
> 2a1. System prompts user with word already exists message
> Use case ends

**Comment by alexehrs** [comment]
Fixed:
*Product description still refers to AB-4's functionality (point 2).
*Describe what LearnV is in the homepage
*My own contact details in contact us adoc

**Comment by RussellOng95** [comment]
v1.1 has been fully implemented.
